version: '3'

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "ljdavies/jazzy-cart-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "ljdavies/jazzy-cart-frontend"
    ports:
      - "3000:3000"
    stdin_open: true
    links:
      - "backend:be"